language: csharp
mono: none
dotnet: 3.1.404
env:
  - SWIFT_VERSION=5.3.1
jobs:
  - name: c, js, ts
    script: make -j2 test-c test-js test-ts
  - name: cpp, py
    install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install libstdc++-9-dev python3.9
    script: make -j2 test-cpp test-py PYTHON=python3.9
  - name: cs
    mono: latest
    script: make -j2 test-cs
  - name: java, error
    script: make -j2 test-java test-error
  - name: swift, cl
    install:
      - wget https://swift.org/builds/swift-$SWIFT_VERSION-release/ubuntu1604/swift-$SWIFT_VERSION-RELEASE/swift-$SWIFT_VERSION-RELEASE-ubuntu16.04.tar.gz
      - tar xf swift-$SWIFT_VERSION-RELEASE-ubuntu16.04.tar.gz -C ..
    script: make -j2 test-swift test-cl SWIFTC=../swift-$SWIFT_VERSION-RELEASE-ubuntu16.04/usr/bin/swiftc
