language: csharp
dist: focal
mono: none
dotnet: 5.0.301
env:
  - SWIFT_VERSION=5.4.1
vm:
  size: large
jobs:
  - name: c, cl
    script: make -j4 test-c test-cl
  - name: cpp, error
    script: make -j4 test-cpp test-error
  - name: cs
    dist: bionic
    mono: latest
    script: make -j4 test-cs
  - name: java
    script: make -j4 test-java
  - name: js, ts
    script: make -j4 test-js test-ts
  - name: py, swift
    install:
      - wget https://swift.org/builds/swift-$SWIFT_VERSION-release/ubuntu2004/swift-$SWIFT_VERSION-RELEASE/swift-$SWIFT_VERSION-RELEASE-ubuntu20.04.tar.gz
      - tar xf swift-$SWIFT_VERSION-RELEASE-ubuntu20.04.tar.gz -C ..
    script: make -j4 test-py test-swift SWIFTC=../swift-$SWIFT_VERSION-RELEASE-ubuntu20.04/usr/bin/swiftc
