language: csharp
dist: focal
mono: none
dotnet: 5.0.400
env:
  - SWIFT_VERSION=5.4.2
vm:
  size: large
jobs:
  - name: js
    script: node --version
  - name: js ts
    script: make -j4 test-js test-ts
