language: csharp
dist: focal
mono: none
dotnet: 5.0.302
env:
  - SWIFT_VERSION=5.4.2
vm:
  size: large
jobs:
  - name: c, cl, error
    script: make -j4 test-c test-cl test-error
  - name: cpp, ts
    script: make -j4 test-cpp test-ts
  - name: cs
    dist: bionic
    mono: latest
    script: make -j4 test-cs
  - name: java, js
    script: make -j4 test-java test-js
  - name: py, swift
    install:
      - wget https://swift.org/builds/swift-$SWIFT_VERSION-release/ubuntu2004/swift-$SWIFT_VERSION-RELEASE/swift-$SWIFT_VERSION-RELEASE-ubuntu20.04.tar.gz
      - tar xf swift-$SWIFT_VERSION-RELEASE-ubuntu20.04.tar.gz -C ..
    script: make -j4 test-py test-swift SWIFTC=../swift-$SWIFT_VERSION-RELEASE-ubuntu20.04/usr/bin/swiftc
